"use strict";

function addChineseCards() {
    console.log('addChineseCards()');
    addHSK1();
    addHSK2();
}
    
function addHSK1() {
    addQuestionAnswersComment("我", ["wǒ"],"wǒ - I; me");
    addQuestionAnswersComment("你",["nǐ"],"nǐ - you (singular)");
    addQuestionAnswersComment("是",["shì"],"shì - be; is; are; am");
    addQuestionAnswersComment("了",["le"],"le - indicates a completed or finished action");
    addQuestionAnswersComment("不",["bù"],"bù - no; not");
    addQuestionAnswersComment("在",["zài"],"zài - at; on; in; indicates an action in progress");
    addQuestionAnswersComment("他",["tā"],"tā - he; him");
    addQuestionAnswersComment("我们",["wǒmen"],"wǒmen - we; us");
    addQuestionAnswersComment("好",["hǎo"],"hǎo - good");
    addQuestionAnswersComment("有",["yǒu"],"yǒu - have");
    addQuestionAnswersComment("这",["zhè"],"zhè - this");
    addQuestionAnswersComment("会",["huì"],"huì - know how to");
    addQuestionAnswersComment("吗",["ma"],"ma - indicates a yes/no question (added to a statement)");
    addQuestionAnswersComment("什么",["shénme"],"shénme - what? (replaces the noun to turn a statement into a question)");
    addQuestionAnswersComment("说",["shuō"],"shuō - speak");
    addQuestionAnswersComment("她",["tā"],"tā - she");
    addQuestionAnswersComment("想",["xiǎng"],"xiǎng - think; believe; suppose; would like to");
    addQuestionAnswersComment("一",["yī"],"yī - one; once; a");
    addQuestionAnswersComment("很",["hěn"],"hěn - very; quite");
    addQuestionAnswersComment("人",["rén"],"rén - person; man; people");
    addQuestionAnswersComment("那",["nà"],"nà - that; then");
    addQuestionAnswersComment("来",["lái"],"lái - come; arrive; ever since; next");
    addQuestionAnswersComment("都",["dōu"],"dōu - all; both");
    addQuestionAnswersComment("个",["ge"],"ge - general measure word");
    addQuestionAnswersComment("能",["néng"],"néng - can; be able");
    addQuestionAnswersComment("去",["qù"],"qù - go; to leave");
    addQuestionAnswersComment("和",["hé"],"hé - and; with");
    addQuestionAnswersComment("做",["zuò"],"zuò - do; make");
    addQuestionAnswersComment("上",["shàng"],"shàng - above; up");
    addQuestionAnswersComment("没有",["méiyǒu"],"méiyǒu - not have; there is not");
    addQuestionAnswersComment("看",["kàn"],"kàn - see; look at; to watch");
    addQuestionAnswersComment("怎么",["zěnme"],"zěnme - how?");
    addQuestionAnswersComment("现在",["xiànzài"],"xiànzài - now");
    addQuestionAnswersComment("点",["diǎn"],"diǎn - a dot; a little; o'clock");
    addQuestionAnswersComment("呢",["ne"],"ne - indicates a question; how about...?;");
    addQuestionAnswersComment("太",["tài"],"tài - too (much)");
    addQuestionAnswersComment("里",["lǐ"],"lǐ - inside; Chinese mile (~.5 km)");
    addQuestionAnswersComment("听",["tīng"],"tīng - listen; hear");
    addQuestionAnswersComment("谁",["shéi"],"shéi - who");
    addQuestionAnswersComment("多",["duō"],"duō - many");
    addQuestionAnswersComment("时候",["shíhou"],"shíhou - time");
    addQuestionAnswersComment("下",["xià"],"xià - fall; below");
    addQuestionAnswersComment("谢谢",["xièxie"],"xièxie - thank you");
    addQuestionAnswersComment("先生",["xiānsheng"],"xiānsheng - Mr.; Sir");
    addQuestionAnswersComment("喜欢",["xǐhuan"],"xǐhuan - to like");
    addQuestionAnswersComment("大",["dà","dài"],"dà, dài - big; large");
    addQuestionAnswersComment("东西",["dōngxi"],"dōngxi - things; stuff");
    addQuestionAnswersComment("小",["xiǎo"],"xiǎo - small; young");
    addQuestionAnswersComment("叫",["jiào"],"jiào - to be called");
    addQuestionAnswersComment("爱",["ài"],"ài - love");
    addQuestionAnswersComment("年",["nián"],"nián - year");
    addQuestionAnswersComment("请",["qǐng"],"qǐng - please; invite; to treat someone to something");
    addQuestionAnswersComment("回",["huí"],"huí - to return; to reply; to go back");
    addQuestionAnswersComment("工作",["gōngzuò"],"gōngzuò - work; a job");
    addQuestionAnswersComment("钱",["qián"],"qián - money; coin");
    addQuestionAnswersComment("吃",["chī"],"chī - eat");
    addQuestionAnswersComment("开",["kāi"],"kāi - to open; to start; to operate (a vehicle)");
    addQuestionAnswersComment("家",["jiā"],"jiā - family; home");
    addQuestionAnswersComment("哪",["nǎ"],"nǎ - which; how");
    addQuestionAnswersComment("朋友",["péngyou"],"péngyou - friend");
    addQuestionAnswersComment("妈妈",["māma"],"māma - mom; mum");
    addQuestionAnswersComment("今天",["jīntiān"],"jīntiān - today");
    addQuestionAnswersComment("几",["jǐ"],"jǐ - how many; several; a few");
    addQuestionAnswersComment("爸爸",["bàba"],"bàba - Dad");
    addQuestionAnswersComment("些",["xiē"],"xiē - some; few; several");
    addQuestionAnswersComment("怎么样",["zěnmeyàng"],"zěnmeyàng - how about?; how is/was it?");
    addQuestionAnswersComment("对不起", ["duìbuqǐ"],"duìbuqǐ - sorry");
    addQuestionAnswersComment("住",["zhù"],"zhù - to live; reside; to stop");
    addQuestionAnswersComment("三",["sān"],"sān - three");
    addQuestionAnswersComment("高兴",["gāoxìng"],"gāoxìng - happy; glad");
    addQuestionAnswersComment("买",["mǎi"],"mǎi - to buy");
    addQuestionAnswersComment("医生",["yīshēng"],"yīshēng - doctor");
    addQuestionAnswersComment("哪儿",["nǎr"],"nǎr - where? (Beijing accent)");
    addQuestionAnswersComment("字",["zì"],"zì - letter; character");
    addQuestionAnswersComment("名字",["míngzi"],"míngzi - name");
    addQuestionAnswersComment("认识",["rènshi"],"rènshi - recognize; know (a person)");
    addQuestionAnswersComment("坐",["zuò"],"zuò - sit");
    addQuestionAnswersComment("喝",["hē"],"hē - to drink");
    addQuestionAnswersComment("写",["xiě"],"xiě - to write; to compose");
    addQuestionAnswersComment("月",["yuè"],"yuè - moon; month; flesh (radical)");
    addQuestionAnswersComment("号",["hào"],"hào - number; day of a month");
    addQuestionAnswersComment("狗",["gǒu"],"gǒu - dog");
    addQuestionAnswersComment("岁",["suì"],"suì - years old; age");
    addQuestionAnswersComment("看见",["kànjiàn"],"kànjiàn - see; catch sight of");
    addQuestionAnswersComment("打电话",["dǎ diànhuà"],"dǎ diànhuà - make a phone call");
    addQuestionAnswersComment("喂",["wèi"],"wèi - hello (on the phone)");
    addQuestionAnswersComment("儿子",["érzi"],"érzi - son");
    addQuestionAnswersComment("漂亮",["piàoliang"],"piàoliang - pretty; beautiful");
    addQuestionAnswersComment("分钟",["fēnzhōng"],"fēnzhōng - minute; (measure word for time)");
    addQuestionAnswersComment("再见",["zàijiàn"],"zàijiàn - goodbye; see you later");
    addQuestionAnswersComment("本",["běn"],"běn - measure word for books");
    addQuestionAnswersComment("明天",["míngtiān"],"míngtiān - tomorrow");
    addQuestionAnswersComment("少",["shǎo"],"shǎo - few; little");
    addQuestionAnswersComment("多少",["duōshao"],"duōshao - how much?; how many?");
    addQuestionAnswersComment("块",["kuài"],"kuài - lump; piece; sum of money");
    addQuestionAnswersComment("女儿",["nǚ'ér"],"nǚ'ér - daughter");
    addQuestionAnswersComment("小姐",["xiǎojie"],"xiǎojie - young lady; miss; Ms.");
    addQuestionAnswersComment("衣服",["yīfu"],"yīfu - clothes");
    addQuestionAnswersComment("水",["shuǐ"],"shuǐ - water");
    addQuestionAnswersComment("学校",["xuéxiào"],"xuéxiào - school");
    addQuestionAnswersComment("电影",["diànyǐng"],"diànyǐng - movie; film");
    addQuestionAnswersComment("书",["shū"],"shū - book; letter");
    addQuestionAnswersComment("四",["sì"],"sì - four");
    addQuestionAnswersComment("五",["wǔ"],"wǔ - five");
    addQuestionAnswersComment("医院",["yīyuàn"],"yīyuàn - hospital");
    addQuestionAnswersComment("没关系",["méi guānxi"],"méi guānxi - it doesn't matter; never mind");
    addQuestionAnswersComment("飞机",["fēijī"],"fēijī - airplane");
    addQuestionAnswersComment("二",["èr"],"èr - two");
    addQuestionAnswersComment("电视",["diànshì"],"diànshì - television; TV");
    addQuestionAnswersComment("读",["dú"],"dú - to read; to study");
    addQuestionAnswersComment("后面",["hòumian"],"hòumian - back; behind");
    addQuestionAnswersComment("昨天",["zuótiān"],"zuótiān - yesterday");
    addQuestionAnswersComment("睡觉",["shuì jiào"],"shuì jiào - to sleep; go to bed");
    addQuestionAnswersComment("六",["liù"],"liù - six");
    addQuestionAnswersComment("老师",["lǎoshī"],"lǎoshī - teacher");
    addQuestionAnswersComment("星期",["xīngqī"],"xīngqī - week");
    addQuestionAnswersComment("十",["shí"],"shí - ten");
    addQuestionAnswersComment("猫",["māo"],"māo - cat");
    addQuestionAnswersComment("电脑",["diànnǎo"],"diànnǎo - computer");
    addQuestionAnswersComment("热",["rè"],"rè - heat; hot");
    addQuestionAnswersComment("学生",["xuésheng"],"xuésheng - student");
    addQuestionAnswersComment("下午",["xiàwǔ"],"xiàwǔ - afternoon");
    addQuestionAnswersComment("学习",["xuéxí"],"xuéxí - learn; to study");
    addQuestionAnswersComment("冷",["lěng"],"lěng - cold");
    addQuestionAnswersComment("不客气",["bú kèqi"],"bú kèqi - you're welcome; don't be polite");
    addQuestionAnswersComment("前面",["qiánmiàn"],"qiánmiàn - in front");
    addQuestionAnswersComment("八",["bā"],"bā - eight");
    addQuestionAnswersComment("中国",["Zhōngguó"],"Zhōngguó - China");
    addQuestionAnswersComment("七",["qī"],"qī - seven");
    addQuestionAnswersComment("菜",["cài"],"cài - dish (type of food); vegetables");
    addQuestionAnswersComment("桌子",["zhuōzi"],"zhuōzi - table; desk");
    addQuestionAnswersComment("出租车",["chūzūchē"],"chūzūchē - taxi; cab");
    addQuestionAnswersComment("天气",["tiānqì"],"tiānqì - weather");
    addQuestionAnswersComment("茶",["chá"],"chá - tea");
    addQuestionAnswersComment("九",["jiǔ"],"jiǔ - nine");
    addQuestionAnswersComment("商店",["shāngdiàn"],"shāngdiàn - shop; store");
    addQuestionAnswersComment("椅子",["yǐzi"],"yǐzi - chair");
    addQuestionAnswersComment("同学",["tóngxué"],"tóngxué - fellow student; schoolmate");
    addQuestionAnswersComment("一点儿",["yìdiǎnr"],"yìdiǎnr - a bit; a few");
    addQuestionAnswersComment("苹果",["píngguǒ"],"píngguǒ - apple");
    addQuestionAnswersComment("饭店",["fàndiàn"],"fàndiàn - restaurant; hotel");
    addQuestionAnswersComment("中午",["zhōngwǔ"],"zhōngwǔ - noon; midday");
    addQuestionAnswersComment("上午",["shàngwǔ"],"shàngwǔ - late morning (before noon)");
    addQuestionAnswersComment("水果",["shuǐguǒ"],"shuǐguǒ - fruit");
    addQuestionAnswersComment("杯子",["bēizi"],"bēizi - cup; glass");
    addQuestionAnswersComment("下雨",["xiàyǔ"],"xiàyǔ - to rain");
    addQuestionAnswersComment("米饭",["mǐfàn"],"mǐfàn - (cooked) rice");
    addQuestionAnswersComment("北京",["Běijīng"],"Běijīng - Beijing");
    addQuestionAnswersComment("汉语",["Hànyǔ"],"Hànyǔ - Chinese language");    
}

function addHSK2() {
    addQuestionAnswersComment("就",["jiù"],"jiù - then; at once; just; only; with regard to");
    addQuestionAnswersComment("要",["yào", "yāo"],"yào, yāo - to want; to need; will/shall; important | demand; request");
    addQuestionAnswersComment("知道",["zhīdao"],"zhīdao - know; be aware of");
    addQuestionAnswersComment("吧",["ba","bā"],"ba, bā - particle indicating polite suggestion; | onomatopoeia | bar (serving drinks, providing internet access, etc.)");
    addQuestionAnswersComment("到",["dào"],"dào - arrive (at a place); until (a time)");
    addQuestionAnswersComment("对",["duì"],"duì - correct; a pair; to face; be opposite; to; towards");
    addQuestionAnswersComment("也",["yě"],"yě - also; too");
    addQuestionAnswersComment("还",["hái","huán"],"hái, huán - still; yet; in addition; even | repay; to return");
    addQuestionAnswersComment("让",["ràng"],"ràng - ask; let; yield");
    addQuestionAnswersComment("给",["gěi","jǐ"],"gěi, jǐ - to give; to grant; (passive particle) | provide");
    addQuestionAnswersComment("过",["guò"],"guò - to pass; to cross; go over; (indicates a past experience)");
    addQuestionAnswersComment("得",["dé","děi","de"],"dé, děi, de - obtain | must | (complement particle)");
    addQuestionAnswersComment("真",["zhēn"],"zhēn - real; true; genuine");
    addQuestionAnswersComment("着",["zhe","zháo","zhuó"],"zhe, zháo, zhuó - -ing (indicating action in progress) | to touch; to feel | to wear; apply");
    addQuestionAnswersComment("可以",["kěyǐ"],"kěyǐ - can; may; possible; okay");
    addQuestionAnswersComment("别",["bié","biè"],"bié, biè - don't do something; don't | depart; | other; difference; distinguish");
    addQuestionAnswersComment("走",["zǒu"],"zǒu - to walk; to go; to move (Kangxi radical 156)");
    addQuestionAnswersComment("告诉",["gàosu"],"gàosu - to tell; inform");
    addQuestionAnswersComment("因为",["yīnwèi"],"yīnwèi - because");
    addQuestionAnswersComment("再",["zài"],"zài - again; once more");
    addQuestionAnswersComment("快",["kuài"],"kuài - fast; quick; swift");
    addQuestionAnswersComment("但是",["dànshì"],"dànshì - but; however");
    addQuestionAnswersComment("已经",["yǐjing"],"yǐjing - already");
    addQuestionAnswersComment("为什么",["wèishénme"],"wèishénme - why?; for what reason?");
    addQuestionAnswersComment("觉得",["juéde"],"juéde - feel; think");
    addQuestionAnswersComment("它",["tā"],"tā - it");
    addQuestionAnswersComment("从",["cóng"],"cóng - from; obey; observe");
    addQuestionAnswersComment("找",["zhǎo"],"zhǎo - try to find; look for; seek; to give change");
    addQuestionAnswersComment("最",["zuì"],"zuì - the most; -est; (indicator for superlative)");
    addQuestionAnswersComment("可能",["kěnéng"],"kěnéng - possible; maybe");
    addQuestionAnswersComment("次",["cì"],"cì - (mw for number of times of occurrence); nth; order");
    addQuestionAnswersComment("出",["chū"],"chū - go out; occur");
    addQuestionAnswersComment("孩子",["háizi"],"háizi - child; children; son or daughter");
    addQuestionAnswersComment("所以",["suǒyǐ"],"suǒyǐ - so; therefore; as a result");
    addQuestionAnswersComment("两",["liǎng"],"liǎng - two; 2; both; (unit of weight equal to 50 grams)");
    addQuestionAnswersComment("错",["cuò"],"cuò - mistake; error; blunder; miss an opportunity");
    addQuestionAnswersComment("等",["děng"],"děng - to wait; rank; equal; etc.");
    addQuestionAnswersComment("题",["tí"],"tí - topic; subject; question on a test or assignment");
    addQuestionAnswersComment("问",["wèn"],"wèn - ask; inquire");
    addQuestionAnswersComment("问题",["wèntí"],"wèntí - question; problem");
    addQuestionAnswersComment("一起",["yìqǐ"],"yìqǐ - together; in the same place");
    addQuestionAnswersComment("开始",["kāishǐ"],"kāishǐ - begin; to start; beginning");
    addQuestionAnswersComment("时间",["shíjiān"],"shíjiān - time; period");
    addQuestionAnswersComment("事情",["shìqing"],"shìqing - matter; affair; thing; business");
    addQuestionAnswersComment("一下",["yíxià"],"yíxià - a little bit/while; one time; once");
    addQuestionAnswersComment("非常",["fēicháng"],"fēicháng - extremely; extraordinary; very");
    addQuestionAnswersComment("希望",["xīwàng"],"xīwàng - to hope; wish for; to desire");
    addQuestionAnswersComment("准备",["zhǔnbèi"],"zhǔnbèi - prepare; get ready");
    addQuestionAnswersComment("比",["bǐ"],"bǐ - compare; (indicates comparison) (Kangxi radical 81); to gesticulate as one talks");
    addQuestionAnswersComment("件",["jiàn"],"jiàn - (mw for things, clothes, and items)");
    addQuestionAnswersComment("意思",["yìsi"],"yìsi - meaning; idea; opinion");
    addQuestionAnswersComment("第一",["dìyī"],"dìyī - first; number 1");
    addQuestionAnswersComment("进",["jìn"],"jìn - enter; come in");
    addQuestionAnswersComment("大家",["dàjiā"],"dàjiā - everyone");
    addQuestionAnswersComment("新",["xīn"],"xīn - new; Xinjiang autonomous region (abbreviation)");
    addQuestionAnswersComment("您",["nín"],"nín - you (polite)");
    addQuestionAnswersComment("穿",["chuān"],"chuān - to wear; put on; penetrate");
    addQuestionAnswersComment("送",["sòng"],"sòng - deliver; to carry; to give; send");
    addQuestionAnswersComment("玩",["wán"],"wán - to play; have a good time; visit; enjoy");
    addQuestionAnswersComment("长",["cháng","zhǎng"],"cháng, zhǎng - long; length | grow; chief (Kangxi radical 168)");
    addQuestionAnswersComment("小时",["xiǎoshí"],"xiǎoshí - hour");
    addQuestionAnswersComment("完",["wán"],"wán - to finish; be over; complete");
    addQuestionAnswersComment("每",["měi"],"měi - each; every");
    addQuestionAnswersComment("公司",["gōngsī"],"gōngsī - company; corporation");
    addQuestionAnswersComment("帮助",["bāngzhù"],"bāngzhù - help; assist; aid");
    addQuestionAnswersComment("晚上",["wǎnshang"],"wǎnshang - evening; night");
    addQuestionAnswersComment("说话",["shuōhuà"],"shuōhuà - to talk; speak");
    addQuestionAnswersComment("门",["mén"],"mén - door; opening; gate (Kangxi radical 169)");
    addQuestionAnswersComment("女",["nǚ"],"nǚ - woman; female (Kangxi radical 38)");
    addQuestionAnswersComment("忙",["máng"],"máng - busy");
    addQuestionAnswersComment("卖",["mài"],"mài - to sell");
    addQuestionAnswersComment("高",["gāo"],"gāo - high; tall (Kangxi radical 189)");
    addQuestionAnswersComment("房间",["fángjiān"],"fángjiān - room");
    addQuestionAnswersComment("路",["lù"],"lù - road; path; journey; route");
    addQuestionAnswersComment("懂",["dǒng"],"dǒng - understand; know");
    addQuestionAnswersComment("正在",["zhèngzài"],"zhèngzài - in the process of (doing something); currently");
    addQuestionAnswersComment("笑",["xiào"],"xiào - to laugh; to smile");
    addQuestionAnswersComment("远",["yuǎn"],"yuǎn - far; distant; remote");
    addQuestionAnswersComment("妻子",["qīzi"],"qīzi - wife");
    addQuestionAnswersComment("丈夫",["zhàngfu"],"zhàngfu - husband; man");
    addQuestionAnswersComment("离",["lí"],"lí - leave; depart; go away; apart from");
    addQuestionAnswersComment("往",["wǎng"],"wǎng - to go (in a direction); towards; in the past");
    addQuestionAnswersComment("男",["nán"],"nán - male");
    addQuestionAnswersComment("眼睛",["yǎnjing"],"yǎnjing - eye");
    addQuestionAnswersComment("快乐",["kuàilè"],"kuàilè - happy");
    addQuestionAnswersComment("虽然",["suīrán"],"suīrán - although; even though");
    addQuestionAnswersComment("早上",["zǎoshang"],"zǎoshang - (early) morning");
    addQuestionAnswersComment("药",["yào"],"yào - medicine; drug; cure; chemical");
    addQuestionAnswersComment("身体",["shēntǐ"],"shēntǐ - health; (human) body");
    addQuestionAnswersComment("黑",["hēi"],"hēi - black; dark (Kangxi radical 203); Heilongjiang province (abbreviation)");
    addQuestionAnswersComment("咖啡",["kāfēi"],"kāfēi - coffee");
    addQuestionAnswersComment("日",["rì"],"rì - sun; day; date; time (Kangxi radical 72)");
    addQuestionAnswersComment("休息",["xiūxi"],"xiūxi - to rest; take a break");
    addQuestionAnswersComment("外",["wài"],"wài - outer; outside; in addition; foreign");
    addQuestionAnswersComment("生日",["shēngrì"],"shēngrì - birthday");
    addQuestionAnswersComment("哥哥",["gēge"],"gēge - older brother");
    addQuestionAnswersComment("票",["piào"],"piào - ticket; bank note; a vote");
    addQuestionAnswersComment("手机",["shǒujī"],"shǒujī - mobile (cell) phone");
    addQuestionAnswersComment("洗",["xǐ"],"xǐ - to wash; bathe");
    addQuestionAnswersComment("跳舞",["tiào wǔ"],"tiào wǔ - to dance");
    addQuestionAnswersComment("弟弟",["dìdi"],"dìdi - younger brother");
    addQuestionAnswersComment("妹妹",["mèimei"],"mèimei - younger sister");
    addQuestionAnswersComment("红",["hóng"],"hóng - red; symbol of success; bonus; popular");
    addQuestionAnswersComment("慢",["màn"],"màn - slow");
    addQuestionAnswersComment("近",["jìn"],"jìn - near; close (to)");
    addQuestionAnswersComment("白",["bái","bó"],"bái, bó - white; snowy; pure; bright; empty (Kangxi radical 106)");
    addQuestionAnswersComment("姐姐",["jiějie"],"jiějie - older sister");
    addQuestionAnswersComment("介绍",["jièshào"],"jièshào - to introduce; recommend; introduction");
    addQuestionAnswersComment("鱼",["yú"],"yú - fish (Kangxi radical 195)");
    addQuestionAnswersComment("累",["lèi","lěi","léi"],"lèi, lěi, léi - tired | accumulate; implicate | rope; bind together");
    addQuestionAnswersComment("课",["kè"],"kè - class; subject; lesson; course");
    addQuestionAnswersComment("上班",["shàng bān"],"shàng bān - go to work; be on duty");
    addQuestionAnswersComment("旁边",["pángbiān"],"pángbiān - side, beside");
    addQuestionAnswersComment("运动",["yùndòng"],"yùndòng - (physical) exercise; movement; sports; campaign");
    addQuestionAnswersComment("去年",["qùnián"],"qùnián - last year");
    addQuestionAnswersComment("报纸",["bàozhǐ"],"bàozhǐ - newspaper");
    addQuestionAnswersComment("颜色",["yánsè"],"yánsè - color");
    addQuestionAnswersComment("机场",["jīchǎng"],"jīchǎng - airport; airfield");
    addQuestionAnswersComment("唱歌",["chànggē"],"chànggē - sing (a song)");
    addQuestionAnswersComment("千",["qiān"],"qiān - one thousand");
    addQuestionAnswersComment("好吃",["hǎochī"],"hǎochī - tasty");
    addQuestionAnswersComment("考试",["kǎoshì"],"kǎoshì - test; exam; to give or take a test");
    addQuestionAnswersComment("左边",["zuǒbian"],"zuǒbian - the left side; the left");
    addQuestionAnswersComment("姓",["xìng"],"xìng - surname; family name");
    addQuestionAnswersComment("百",["bǎi"],"bǎi - hundred");
    addQuestionAnswersComment("雪",["xuě"],"xuě - snow");
    addQuestionAnswersComment("贵",["guì"],"guì - expensive; noble; honorable; Guizhou province (abbreviation)");
    addQuestionAnswersComment("生病",["shēng bìng"],"shēng bìng - get sick; fall ill");
    addQuestionAnswersComment("游泳",["yóuyǒng"],"yóuyǒng - to swim");
    addQuestionAnswersComment("牛奶",["niúnǎi"],"niúnǎi - cow's milk");
    addQuestionAnswersComment("右边",["yòubian"],"yòubian - the right (as opposed to left) side");
    addQuestionAnswersComment("便宜",["piányi"],"piányi - cheap");
    addQuestionAnswersComment("公共汽车",["gōnggòng qìchē"],"gōnggòng qìchē - (public) bus");
    addQuestionAnswersComment("起床",["qǐ chuáng"],"qǐ chuáng - get out of bed");
    addQuestionAnswersComment("打篮球",["dǎ lánqiú"],"dǎ lánqiú - play basketball");
    addQuestionAnswersComment("鸡蛋",["jīdàn"],"jīdàn - (chicken) egg");
    addQuestionAnswersComment("踢足球",["tīzúqiú"],"tīzúqiú - to play football/soccer");
    addQuestionAnswersComment("零",["líng"],"líng - zero; remnant");
    addQuestionAnswersComment("手表",["shǒubiǎo"],"shǒubiǎo - wristwatch");
    addQuestionAnswersComment("旅游",["lǚyóu"],"lǚyóu - trip; journey; tour");
    addQuestionAnswersComment("服务员",["fúwùyuán"],"fúwùyuán - waiter/waitress; server; attendant");
    addQuestionAnswersComment("宾馆",["bīnguǎn"],"bīnguǎn - guesthouse; hotel");
    addQuestionAnswersComment("教室",["jiàoshì"],"jiàoshì - classroom");
    addQuestionAnswersComment("跑步",["pǎo bù"],"pǎo bù - to run; to jog");
    addQuestionAnswersComment("阴",["yīn"],"yīn - cloudy (weather); yin (the negative principle of Yin and Yang); secret; the moon; negative; shade");
    addQuestionAnswersComment("面条",["miàntiáo"],"miàntiáo - noodles");
    addQuestionAnswersComment("铅笔",["qiānbǐ"],"qiānbǐ - pencil");
    addQuestionAnswersComment("火车站",["huǒchēzhàn"],"huǒchēzhàn - train station");
    addQuestionAnswersComment("西瓜",["xīguā"],"xīguā - watermelon");
    addQuestionAnswersComment("羊肉",["yángròu"],"yángròu - mutton; lamb");
    addQuestionAnswersComment("晴",["qíng"],"qíng - clear; fine (as of weather)");
}

