"use strict";

function addChineseCards() {
    console.log('addChineseCards()');
	addQuestionAnswersComment("我",["wǒ"],"wǒ - I; me");
	addQuestionAnswersComment("你",["nǐ"],"nǐ - you (singular)");
	addQuestionAnswersComment("是",["shì"],"shì - be; is; are; am");
	addQuestionAnswersComment("了",["le"],"le - indicates a completed or finished action");
	addQuestionAnswersComment("不",["bù"],"bù - no; not");
	addQuestionAnswersComment("在",["zài"],"zài - at; on; in; indicates an action in progress");
	addQuestionAnswersComment("他",["tā"],"tā - he; him");
	addQuestionAnswersComment("我们",["wǒmen"],"wǒmen - we; us");
	addQuestionAnswersComment("好",["hǎo"],"hǎo - good");
	addQuestionAnswersComment("有",["yǒu"],"yǒu - have");
	addQuestionAnswersComment("这",["zhè"],"zhè - this");
	addQuestionAnswersComment("会",["huì"],"huì - know how to");
	addQuestionAnswersComment("吗",["ma"],"ma - indicates a yes/no question (added to a statement)");
	addQuestionAnswersComment("什么",["shénme"],"shénme - what? (replaces the noun to turn a statement into a question)");
	addQuestionAnswersComment("说",["shuō"],"shuō - speak");
	addQuestionAnswersComment("她",["tā"],"tā - she");
	addQuestionAnswersComment("想",["xiǎng"],"xiǎng - think; believe; suppose; would like to");
	addQuestionAnswersComment("一",["yī"],"yī - one; once; a");
	addQuestionAnswersComment("很",["hěn"],"hěn - very; quite");
	addQuestionAnswersComment("人",["rén"],"rén - person; man; people");
	addQuestionAnswersComment("那",["nà"],"nà - that; then");
	addQuestionAnswersComment("来",["lái"],"lái - come; arrive; ever since; next");
	addQuestionAnswersComment("都",["dōu"],"dōu - all; both");
	addQuestionAnswersComment("个",["ge"],"ge - general measure word");
	addQuestionAnswersComment("能",["néng"],"néng - can; be able");
	addQuestionAnswersComment("去",["qù"],"qù - go; to leave");
	addQuestionAnswersComment("和",["hé"],"hé - and; with");
	addQuestionAnswersComment("做",["zuò"],"zuò - do; make");
	addQuestionAnswersComment("上",["shàng"],"shàng - above; up");
	addQuestionAnswersComment("没有",["méiyǒu"],"méiyǒu - not have; there is not");
	addQuestionAnswersComment("看",["kàn"],"kàn - see; look at; to watch");
	addQuestionAnswersComment("怎么",["zěnme"],"zěnme - how?");
	addQuestionAnswersComment("现在",["xiànzài"],"xiànzài - now");
	addQuestionAnswersComment("点",["diǎn"],"diǎn - a dot; a little; o'clock");
	addQuestionAnswersComment("呢",["ne"],"ne - indicates a question; how about...?;");
	addQuestionAnswersComment("太",["tài"],"tài - too (much)");
	addQuestionAnswersComment("里",["lǐ"],"lǐ - inside; Chinese mile (~.5 km)");
	addQuestionAnswersComment("听",["tīng"],"tīng - listen; hear");
	addQuestionAnswersComment("谁",["shéi"],"shéi - who");
	addQuestionAnswersComment("多",["duō"],"duō - many");
	addQuestionAnswersComment("时候",["shíhou"],"shíhou - time");
	addQuestionAnswersComment("下",["xià"],"xià - fall; below");
	addQuestionAnswersComment("谢谢",["xièxie"],"xièxie - thank you");
	addQuestionAnswersComment("先生",["xiānsheng"],"xiānsheng - Mr.; Sir");
	addQuestionAnswersComment("喜欢",["xǐhuan"],"xǐhuan - to like");
	addQuestionAnswersComment("大",["dà", "dài"],"dà, dài - big; large");
	addQuestionAnswersComment("东西",["dōngxi"],"dōngxi - things; stuff");
	addQuestionAnswersComment("小",["xiǎo"],"xiǎo - small; young");
	addQuestionAnswersComment("叫",["jiào"],"jiào - to be called");
	addQuestionAnswersComment("爱",["ài"],"ài - love");
	addQuestionAnswersComment("年",["nián"],"nián - year");
	addQuestionAnswersComment("请",["qǐng"],"qǐng - please; invite; to treat someone to something");
	addQuestionAnswersComment("回",["huí"],"huí - to return; to reply; to go back");
	addQuestionAnswersComment("工作",["gōngzuò"],"gōngzuò - work; a job");
	addQuestionAnswersComment("钱",["qián"],"qián - money; coin");
	addQuestionAnswersComment("吃",["chī"],"chī - eat");
	addQuestionAnswersComment("开",["kāi"],"kāi - to open; to start; to operate (a vehicle)");
	addQuestionAnswersComment("家",["jiā"],"jiā - family; home");
	addQuestionAnswersComment("哪",["nǎa"],"nǎa - which; how");
	addQuestionAnswersComment("朋友",["péngyou"],"péngyou - friend");
	addQuestionAnswersComment("妈妈",["māma"],"māma - mom; mum");
	addQuestionAnswersComment("今天",["jīntiān"],"jīntiān - today");
	addQuestionAnswersComment("几",["jǐ"],"jǐ - how many; several; a few");
	addQuestionAnswersComment("爸爸",["bàba"],"bàba - Dad");
	addQuestionAnswersComment("些",["xiē"],"xiē - some; few; several");
	addQuestionAnswersComment("怎么样",["zěnmeyàng"],"zěnmeyàng - how about?; how is/was it?");
	addQuestionAnswersComment("对不起", ["duìbuqǐ"],"duìbuqǐ - sorry");
	addQuestionAnswersComment("住",["zhù"],"zhù - to live; reside; to stop");
	addQuestionAnswersComment("三",["sān"],"sān - three");
	addQuestionAnswersComment("高兴",["gāoxìng"],"gāoxìng - happy; glad");
	addQuestionAnswersComment("买",["mǎi"],"mǎi - to buy");
	addQuestionAnswersComment("医生",["yīshēng"],"yīshēng - doctor");
	addQuestionAnswersComment("哪儿",["nǎr"],"nǎr - where? (Beijing accent)");
	addQuestionAnswersComment("字",["zì"],"zì - letter; character");
	addQuestionAnswersComment("名字",["míngzi"],"míngzi - name");
	addQuestionAnswersComment("认识",["rènshi"],"rènshi - recognize; know (a person)");
	addQuestionAnswersComment("坐",["zuò"],"zuò - sit");
	addQuestionAnswersComment("喝",["hē"],"hē - to drink");
	addQuestionAnswersComment("写",["xiě"],"xiě - to write; to compose");
	addQuestionAnswersComment("月",["yuè"],"yuè - moon; month; flesh (radical)");
	addQuestionAnswersComment("号",["hào"],"hào - number; day of a month");
	addQuestionAnswersComment("狗",["gǒu"],"gǒu - dog");
	addQuestionAnswersComment("岁",["suì"],"suì - years old; age");
	addQuestionAnswersComment("看见",["kànjiàn"],"kànjiàn - see; catch sight of");
	addQuestionAnswersComment("打电话",["dǎ diànhuà"],"dǎ diànhuà - make a phone call");
	addQuestionAnswersComment("喂",["wèi"],"wèi - hello (on the phone)");
	addQuestionAnswersComment("儿子",["érzi"],"érzi - son");
	addQuestionAnswersComment("漂亮",["piàoliang"],"piàoliang - pretty; beautiful");
	addQuestionAnswersComment("分钟",["fēnzhōng"],"fēnzhōng - minute; (measure word for time)");
	addQuestionAnswersComment("再见",["zàijiàn"],"zàijiàn - goodbye; see you later");
	addQuestionAnswersComment("本",["běn"],"běn - measure word for books");
	addQuestionAnswersComment("明天",["míngtiān"],"míngtiān - tomorrow");
	addQuestionAnswersComment("少",["shǎo"],"shǎo - few; little");
	addQuestionAnswersComment("多少",["duōshao"],"duōshao - how much?; how many?");
	addQuestionAnswersComment("块",["kuài"],"kuài - lump; piece; sum of money");
	addQuestionAnswersComment("女儿",["nǚ'ér"],"nǚ'ér - daughter");
	addQuestionAnswersComment("小姐",["xiǎojie"],"xiǎojie - young lady; miss; Ms.");
	addQuestionAnswersComment("衣服",["yīfu"],"yīfu - clothes");
	addQuestionAnswersComment("水",["shuǐ"],"shuǐ - water");
	addQuestionAnswersComment("学校",["xuéxiào"],"xuéxiào - school");
	addQuestionAnswersComment("电影",["diànyǐng"],"diànyǐng - movie; film");
	addQuestionAnswersComment("书",["shū"],"shū - book; letter");
	addQuestionAnswersComment("四",["sì"],"sì - four");
	addQuestionAnswersComment("五",["wǔ"],"wǔ - five");
	addQuestionAnswersComment("医院",["yīyuàn"],"yīyuàn - hospital");
	addQuestionAnswersComment("没关系",["méi guānxi"],"méi guānxi - it doesn't matter; never mind");
	addQuestionAnswersComment("飞机",["fēijī"],"fēijī - airplane");
	addQuestionAnswersComment("二",["èr"],"èr - two");
	addQuestionAnswersComment("电视",["diànshì"],"diànshì - television; TV");
	addQuestionAnswersComment("读",["dú"],"dú - to read; to study");
	addQuestionAnswersComment("后面",["hòumian"],"hòumian - back; behind");
	addQuestionAnswersComment("昨天",["zuótiān"],"zuótiān - yesterday");
	addQuestionAnswersComment("睡觉",["shuì jiào"],"shuì jiào - to sleep; go to bed");
	addQuestionAnswersComment("六",["liù"],"liù - six");
	addQuestionAnswersComment("老师",["lǎoshī"],"lǎoshī - teacher");
	addQuestionAnswersComment("星期",["xīngqī"],"xīngqī - week");
	addQuestionAnswersComment("十",["shí"],"shí - ten");
	addQuestionAnswersComment("猫",["māo"],"māo - cat");
	addQuestionAnswersComment("电脑",["diànnǎo"],"diànnǎo - computer");
	addQuestionAnswersComment("热",["rè"],"rè - heat; hot");
	addQuestionAnswersComment("学生",["xuésheng"],"xuésheng - student");
	addQuestionAnswersComment("下午",["xiàwǔ"],"xiàwǔ - afternoon");
	addQuestionAnswersComment("学习",["xuéxí"],"xuéxí - learn; to study");
	addQuestionAnswersComment("冷",["lěng"],"lěng - cold");
	addQuestionAnswersComment("不客气",["bú kèqi"],"bú kèqi - you're welcome; don't be polite");
	addQuestionAnswersComment("前面",["qiánmiàn"],"qiánmiàn - in front");
	addQuestionAnswersComment("八",["bā"],"bā - eight");
	addQuestionAnswersComment("中国",["Zhōngguó"],"Zhōngguó - China");
	addQuestionAnswersComment("七",["qī"],"qī - seven");
	addQuestionAnswersComment("菜",["cài"],"cài - dish (type of food); vegetables");
	addQuestionAnswersComment("桌子",["zhuōzi"],"zhuōzi - table; desk");
	addQuestionAnswersComment("出租车",["chūzūchē"],"chūzūchē - taxi; cab");
	addQuestionAnswersComment("天气",["tiānqì"],"tiānqì - weather");
	addQuestionAnswersComment("茶",["chá"],"chá - tea");
	addQuestionAnswersComment("九",["jiǔ"],"jiǔ - nine");
	addQuestionAnswersComment("商店",["shāngdiàn"],"shāngdiàn - shop; store");
	addQuestionAnswersComment("椅子",["yǐzi"],"yǐzi - chair");
	addQuestionAnswersComment("同学",["tóngxué"],"tóngxué - fellow student; schoolmate");
	addQuestionAnswersComment("一点儿",["yìdiǎnr"],"yìdiǎnr - a bit; a few");
	addQuestionAnswersComment("苹果",["píngguǒ"],"píngguǒ - apple");
	addQuestionAnswersComment("饭店",["fàndiàn"],"fàndiàn - restaurant; hotel");
	addQuestionAnswersComment("中午",["zhōngwǔ"],"zhōngwǔ - noon; midday");
	addQuestionAnswersComment("上午",["shàngwǔ"],"shàngwǔ - late morning (before noon)");
	addQuestionAnswersComment("水果",["shuǐguǒ"],"shuǐguǒ - fruit");
	addQuestionAnswersComment("杯子",["bēizi"],"bēizi - cup; glass");
	addQuestionAnswersComment("下雨",["xiàyǔ"],"xiàyǔ - to rain");
	addQuestionAnswersComment("米饭",["mǐfàn"],"mǐfàn - (cooked) rice");
	addQuestionAnswersComment("北京",["Běijīng"],"Běijīng - Beijing");
	addQuestionAnswersComment("汉语",["Hànyǔ"],"Hànyǔ - Chinese language");    
}

