"use strict";

function addChineseCards() {
    console.log('addChineseCards()');
	addQuestionAnswerComment("我","wǒ","wǒ - I; me");
	addQuestionAnswerComment("你","nǐ","nǐ - you (singular)");
	addQuestionAnswerComment("是","shì","shì - be; is; are; am");
	addQuestionAnswerComment("了","le","le - indicates a completed or finished action");
	addQuestionAnswerComment("不","bù","bù - no; not");
	addQuestionAnswerComment("在","zài","zài - at; on; in; indicates an action in progress");
	addQuestionAnswerComment("他","tā","tā - he; him");
	addQuestionAnswerComment("我们","wǒmen","wǒmen - we; us");
	addQuestionAnswerComment("好","hǎo","hǎo - good");
	addQuestionAnswerComment("有","yǒu","yǒu - have");
	addQuestionAnswerComment("这","zhè","zhè - this");
	addQuestionAnswerComment("会","huì","huì - know how to");
	addQuestionAnswerComment("吗","ma","ma - indicates a yes/no question (added to a statement)");
	addQuestionAnswerComment("什么","shénme","shénme - what? (replaces the noun to turn a statement into a question)");
	addQuestionAnswerComment("说","shuō","shuō - speak");
	addQuestionAnswerComment("她","tā","tā - she");
	addQuestionAnswerComment("想","xiǎng","xiǎng - think; believe; suppose; would like to");
	addQuestionAnswerComment("一","yī","yī - one; once; a");
	addQuestionAnswerComment("很","hěn","hěn - very; quite");
	addQuestionAnswerComment("人","rén","rén - person; man; people");
	addQuestionAnswerComment("那","nà","nà - that; then");
	addQuestionAnswerComment("来","lái","lái - come; arrive; ever since; next");
	addQuestionAnswerComment("都","dōu","dōu - all; both");
	addQuestionAnswerComment("个","ge","ge - general measure word");
	addQuestionAnswerComment("能","néng","néng - can; be able");
	addQuestionAnswerComment("去","qù","qù - go; to leave");
	addQuestionAnswerComment("和","hé","hé - and; with");
	addQuestionAnswerComment("做","zuò","zuò - do; make");
	addQuestionAnswerComment("上","shàng","shàng - above; up");
	addQuestionAnswerComment("没有","méiyǒu","méiyǒu - not have; there is not");
	addQuestionAnswerComment("看","kàn","kàn - see; look at; to watch");
	addQuestionAnswerComment("怎么","zěnme","zěnme - how?");
	addQuestionAnswerComment("现在","xiànzài","xiànzài - now");
	addQuestionAnswerComment("点","diǎn","diǎn - a dot; a little; o'clock");
	addQuestionAnswerComment("呢","ne","ne - indicates a question; how about...?;");
	addQuestionAnswerComment("太","tài","tài - too (much)");
	addQuestionAnswerComment("里","lǐ","lǐ - inside; Chinese mile (~.5 km)");
	addQuestionAnswerComment("听","tīng","tīng - listen; hear");
	addQuestionAnswerComment("谁","shéi","shéi - who");
	addQuestionAnswerComment("多","duō","duō - many");
	addQuestionAnswerComment("时候","shíhou","shíhou - time");
	addQuestionAnswerComment("下","xià","xià - fall; below");
	addQuestionAnswerComment("谢谢","xièxie","xièxie - thank you");
	addQuestionAnswerComment("先生","xiānsheng","xiānsheng - Mr.; Sir");
	addQuestionAnswerComment("喜欢","xǐhuan","xǐhuan - to like");
	addQuestionAnswerComment("大","dà, dài","dà, dài - big; large");
	addQuestionAnswerComment("东西","dōngxi","dōngxi - things; stuff");
	addQuestionAnswerComment("小","xiǎo","xiǎo - small; young");
	addQuestionAnswerComment("叫","jiào","jiào - to be called");
	addQuestionAnswerComment("爱","ài","ài - love");
	addQuestionAnswerComment("年","nián","nián - year");
	addQuestionAnswerComment("请","qǐng","qǐng - please; invite; to treat someone to something");
	addQuestionAnswerComment("回","huí","huí - to return; to reply; to go back");
	addQuestionAnswerComment("工作","gōngzuò","gōngzuò - work; a job");
	addQuestionAnswerComment("钱","qián","qián - money; coin");
	addQuestionAnswerComment("吃","chī","chī - eat");
	addQuestionAnswerComment("开","kāi","kāi - to open; to start; to operate (a vehicle)");
	addQuestionAnswerComment("家","jiā","jiā - family; home");
	addQuestionAnswerComment("哪","nǎa","nǎa - which; how");
	addQuestionAnswerComment("朋友","péngyou","péngyou - friend");
	addQuestionAnswerComment("妈妈","māma","māma - mom; mum");
	addQuestionAnswerComment("今天","jīntiān","jīntiān - today");
	addQuestionAnswerComment("几","jǐ","jǐ - how many; several; a few");
	addQuestionAnswerComment("爸爸","bàba","bàba - Dad");
	addQuestionAnswerComment("些","xiē","xiē - some; few; several");
	addQuestionAnswerComment("怎么样","zěnmeyàng","zěnmeyàng - how about?; how is/was it?");
	addQuestionAnswerComment("对不起","duìbuqǐ","duìbuqǐ - sorry");
	addQuestionAnswerComment("住","zhù","zhù - to live; reside; to stop");
	addQuestionAnswerComment("三","sān","sān - three");
	addQuestionAnswerComment("高兴","gāoxìng","gāoxìng - happy; glad");
	addQuestionAnswerComment("买","mǎi","mǎi - to buy");
	addQuestionAnswerComment("医生","yīshēng","yīshēng - doctor");
	addQuestionAnswerComment("哪儿","nǎr","nǎr - where? (Beijing accent)");
	addQuestionAnswerComment("字","zì","zì - letter; character");
	addQuestionAnswerComment("名字","míngzi","míngzi - name");
	addQuestionAnswerComment("认识","rènshi","rènshi - recognize; know (a person)");
	addQuestionAnswerComment("坐","zuò","zuò - sit");
	addQuestionAnswerComment("喝","hē","hē - to drink");
	addQuestionAnswerComment("写","xiě","xiě - to write; to compose");
	addQuestionAnswerComment("月","yuè","yuè - moon; month; flesh (radical)");
	addQuestionAnswerComment("号","hào","hào - number; day of a month");
	addQuestionAnswerComment("狗","gǒu","gǒu - dog");
	addQuestionAnswerComment("岁","suì","suì - years old; age");
	addQuestionAnswerComment("看见","kànjiàn","kànjiàn - see; catch sight of");
	addQuestionAnswerComment("打电话","dǎ diànhuà","dǎ diànhuà - make a phone call");
	addQuestionAnswerComment("喂","wèi","wèi - hello (on the phone)");
	addQuestionAnswerComment("儿子","érzi","érzi - son");
	addQuestionAnswerComment("漂亮","piàoliang","piàoliang - pretty; beautiful");
	addQuestionAnswerComment("分钟","fēnzhōng","fēnzhōng - minute; (measure word for time)");
	addQuestionAnswerComment("再见","zàijiàn","zàijiàn - goodbye; see you later");
	addQuestionAnswerComment("本","běn","běn - measure word for books");
	addQuestionAnswerComment("明天","míngtiān","míngtiān - tomorrow");
	addQuestionAnswerComment("少","shǎo","shǎo - few; little");
	addQuestionAnswerComment("多少","duōshao","duōshao - how much?; how many?");
	addQuestionAnswerComment("块","kuài","kuài - lump; piece; sum of money");
	addQuestionAnswerComment("女儿","nǚ'ér","nǚ'ér - daughter");
	addQuestionAnswerComment("小姐","xiǎojie","xiǎojie - young lady; miss; Ms.");
	addQuestionAnswerComment("衣服","yīfu","yīfu - clothes");
	addQuestionAnswerComment("水","shuǐ","shuǐ - water");
	addQuestionAnswerComment("学校","xuéxiào","xuéxiào - school");
	addQuestionAnswerComment("电影","diànyǐng","diànyǐng - movie; film");
	addQuestionAnswerComment("书","shū","shū - book; letter");
	addQuestionAnswerComment("四","sì","sì - four");
	addQuestionAnswerComment("五","wǔ","wǔ - five");
	addQuestionAnswerComment("医院","yīyuàn","yīyuàn - hospital");
	addQuestionAnswerComment("没关系","méi guānxi","méi guānxi - it doesn't matter; never mind");
	addQuestionAnswerComment("飞机","fēijī","fēijī - airplane");
	addQuestionAnswerComment("二","èr","èr - two");
	addQuestionAnswerComment("电视","diànshì","diànshì - television; TV");
	addQuestionAnswerComment("读","dú","dú - to read; to study");
	addQuestionAnswerComment("后面","hòumian","hòumian - back; behind");
	addQuestionAnswerComment("昨天","zuótiān","zuótiān - yesterday");
	addQuestionAnswerComment("睡觉","shuì jiào","shuì jiào - to sleep; go to bed");
	addQuestionAnswerComment("六","liù","liù - six");
	addQuestionAnswerComment("老师","lǎoshī","lǎoshī - teacher");
	addQuestionAnswerComment("星期","xīngqī","xīngqī - week");
	addQuestionAnswerComment("十","shí","shí - ten");
	addQuestionAnswerComment("猫","māo","māo - cat");
	addQuestionAnswerComment("电脑","diànnǎo","diànnǎo - computer");
	addQuestionAnswerComment("热","rè","rè - heat; hot");
	addQuestionAnswerComment("学生","xuésheng","xuésheng - student");
	addQuestionAnswerComment("下午","xiàwǔ","xiàwǔ - afternoon");
	addQuestionAnswerComment("学习","xuéxí","xuéxí - learn; to study");
	addQuestionAnswerComment("冷","lěng","lěng - cold");
	addQuestionAnswerComment("不客气","bú kèqi","bú kèqi - you're welcome; don't be polite");
	addQuestionAnswerComment("前面","qiánmiàn","qiánmiàn - in front");
	addQuestionAnswerComment("八","bā","bā - eight");
	addQuestionAnswerComment("中国","Zhōngguó","Zhōngguó - China");
	addQuestionAnswerComment("七","qī","qī - seven");
	addQuestionAnswerComment("菜","cài","cài - dish (type of food); vegetables");
	addQuestionAnswerComment("桌子","zhuōzi","zhuōzi - table; desk");
	addQuestionAnswerComment("出租车","chūzūchē","chūzūchē - taxi; cab");
	addQuestionAnswerComment("天气","tiānqì","tiānqì - weather");
	addQuestionAnswerComment("茶","chá","chá - tea");
	addQuestionAnswerComment("九","jiǔ","jiǔ - nine");
	addQuestionAnswerComment("商店","shāngdiàn","shāngdiàn - shop; store");
	addQuestionAnswerComment("椅子","yǐzi","yǐzi - chair");
	addQuestionAnswerComment("同学","tóngxué","tóngxué - fellow student; schoolmate");
	addQuestionAnswerComment("一点儿","yìdiǎnr","yìdiǎnr - a bit; a few");
	addQuestionAnswerComment("苹果","píngguǒ","píngguǒ - apple");
	addQuestionAnswerComment("饭店","fàndiàn","fàndiàn - restaurant; hotel");
	addQuestionAnswerComment("中午","zhōngwǔ","zhōngwǔ - noon; midday");
	addQuestionAnswerComment("上午","shàngwǔ","shàngwǔ - late morning (before noon)");
	addQuestionAnswerComment("水果","shuǐguǒ","shuǐguǒ - fruit");
	addQuestionAnswerComment("杯子","bēizi","bēizi - cup; glass");
	addQuestionAnswerComment("下雨","xiàyǔ","xiàyǔ - to rain");
	addQuestionAnswerComment("米饭","mǐfàn","mǐfàn - (cooked) rice");
	addQuestionAnswerComment("北京","Běijīng","Běijīng - Beijing");
	addQuestionAnswerComment("汉语","Hànyǔ","Hànyǔ - Chinese language");    
}

