runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js
  
- url: /css
  static_dir: css
  
- url: /png
  static_dir: png
  
- url: /menu
  static_dir: menu

- url: /html
  static_dir: html
  
#- url: /favicon.ico
#  static_files: favicon.ico
#  upload: favicon.ico
  
#- url: /
#  static_files: index\.html
#  upload: index\.html

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /course.*
  script: course.app
  secure: always
  redirect_http_response_code: 301  

- url: /data/.*
  script: data.app
  secure: always
  redirect_http_response_code: 301  
  
  
- url: /.*
  script: main.app
  secure: always
  redirect_http_response_code: 301

