runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js
  
- url: /css
  static_dir: css
  
- url: /png
  static_dir: png
  
- url: /menu
  static_dir: menu
  
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  
#- url: /
#  static_files: index\.html
#  upload: index\.html
  
- url: /.*
  script: main.app
  login: required
